version: '3'

services:
  backend:
    build:
      context: ./APITEST
    networks:
      - gateway
    command: gunicorn APITEST.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - gateway
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
networks:
  gateway: {}
volumes:
    static_volume: {}
